### ISSUE TITLE
[Upstream] No way to specify upstream (backend) protocol

### ISSUE THREAD

**Issue by carlisia** [knative-extensions/net-gateway-api#367]
Ref.: https://github.com/kubernetes-sigs/gateway-api/discussions/1244.

**Comment by anhdle14** [comment]
```
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  annotations:
    networking.internal.knative.dev/rollout: '{"configurations":[{"configurationName":"hello","percent":100,"revisions":[{"revisionName":"hello-00001","percent":100}],"stepParams":{}}]}'
    networking.knative.dev/ingress.class: gateway-api.ingress.networking.knative.dev
    serving.knative.dev/creator: anhdle14@icloud.com
    serving.knative.dev/lastModifier: anhdle14@icloud.com
  creationTimestamp: "2023-04-02T19:20:34Z"
  generation: 3
  labels:
    networking.knative.dev/visibility: ""
    serving.knative.dev/route: hello
    serving.knative.dev/routeNamespace: default
    serving.knative.dev/service: hello
  name: hello.default.knative.ts.anhdle14.me
  namespace: default
spec:
  hostnames:
  - hello.default.knative.ts.anhdle14.me
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    sectionName: http # THIS IS MISSING RIGHT NOW
    name: knative-gateway
    namespace: istio-system
  rules:
  - backendRefs:
    - filters:
      - requestHeaderModifier:
          set:
          - name: Knative-Serving-Revision
            value: hello-00001
          - name: Knative-Serving-Namespace
            value: default
        type: RequestHeaderModifier
      group: ""
      kind: Service
      name: hello-00001
      port: 80
      weight: 100
    filters:
    - requestHeaderModifier:
        set:
        - name: K-Network-Hash
          value: d5e6e76864e0485d5d3e37426c6f081d0efba24af58e6a9285cb6cc55cb64dc9
      type: RequestHeaderModifier
    matches:
    - headers:
      - name: K-Network-Hash
        type: Exact
        value: override
      path:
        type: PathPrefix
        value: /
  - backendRefs:
    - filters:
      - requestHeaderModifier:
          set:
          - name: Knative-Serving-Revision
            value: hello-00001
          - name: Knative-Serving-Namespace
            value: default
        type: RequestHeaderModifier
      group: ""
      kind: Service
      name: hello-00001
      port: 80
      weight: 100
    matches:
    - path:
        type: PathPrefix
        value: /
```

Also I couldn't make `auto-tls` work with TERMINATION on Gateway level:

```
---
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: knative-gateway
  namespace: istio-system
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "*.knative.ts.anhdle14.me"
spec:
  gatewayClassName: istio
  listeners:
    - name: http
      hostname: "*.knative.ts.anhdle14.me"
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      hostname: "*.knative.ts.anhdle14.me"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: knative-ts-anhdle14-me-tls
      allowedRoutes:
        namespaces:
          from: All
```

Could we provide anyway to allow `config-gateway` to allow some templates to be used when generating `*Route` resource?
