### ISSUE TITLE
Please support gRPC Service

### ISSUE THREAD

**Issue by kahirokunn** [knative-extensions/net-gateway-api#402]
`gRPC Service` does not work.

Here is an example.

server yaml.

```yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: grpc-ping
  namespace: default
  labels:
    networking.knative.dev/visibility: cluster-local
spec:
  template:
    spec:
      containers:
      - image: kahiro/grpc-ping-go:latest
        ports:
          - name: h2c
            containerPort: 8080
```

client yaml.
This is an error.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: grpc-ping-client
  namespace: default
spec:
  containers:
  - args:
    - /client
    - -server_addr
    - grpc-ping.default.svc.cluster.local:80
    - -insecure
    image: kahiro/grpc-ping-go:latest
    imagePullPolicy: Always
    name: grpc-ping-client
```

client yaml.
This works.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: grpc-ping-client-pod
  namespace: default
spec:
  containers:
  - args:
    - /client
    - -server_addr
    - 10-0-3-236.default.pod.cluster.local:8080
    - -insecure
    image: kahiro/grpc-ping-go:latest
    imagePullPolicy: Always
    name: grpc-ping-client
```

The difference between the two above is that they go through a Gateway configured with HTTPRoute or not.
`TCPRoute` or `GRPCRoute` must also be used.

https://gateway-api.sigs.k8s.io/concepts/api-overview/?h=grpcroute#route-resources
