### ISSUE TITLE
I currently want to make the service to be exposed so that `80 -> 443 -> https` automatically with TLS Termination at Gateway level. However I couldn't able to do anything with `config-networking`, `config-gateway`, `config-domain`.

### ISSUE THREAD

**Issue by dprotaso** [knative-extensions/net-gateway-api#477]
I currently want to make the service to be exposed so that `80 -> 443 -> https` automatically with TLS Termination at Gateway level. However I couldn't able to do anything with `config-networking`, `config-gateway`, `config-domain`.

I was able to make it work with `http-80` though the HTTPRoute generated are only using 80. I want to be able to generate using this format:

<summary>httpbin redirect httproute sample</summary>

```yaml
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: 80-http-httpbin
  namespace: httpbin
spec:
  hostnames:
    - "httpbin.ts.anhdle14.me"
  parentRefs:
    - name: l7-ts-gateway
      sectionName: http
      namespace: istio-system
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
            port: 443
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: 443-https-httpbin
  namespace: httpbin
spec:
  hostnames:
    - "httpbin.ts.anhdle14.me"
  parentRefs:
    - name: l7-ts-gateway
      sectionName: https
      namespace: istio-system
  rules:
    - backendRefs:
        - name: httpbin
          port: 80
```

</details>

<summary>What being currently generated now.</summary>

```yaml
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  annotations:
    networking.internal.knative.dev/rollout: '{"configurations":[{"configurationName":"hello","percent":100,"revisions":[{"revisionName":"hello-00001","percent":100}],"stepParams":{}}]}'
    networking.knative.dev/ingress.class: gateway-api.ingress.networking.knative.dev
    serving.knative.dev/creator: anhdle14@icloud.com
    serving.knative.dev/lastModifier: anhdle14@icloud.com
  creationTimestamp: "2023-04-02T19:20:34Z"
  generation: 3
  labels:
    networking.knative.dev/visibility: ""
    serving.knative.dev/route: hello
    serving.knative.dev/routeNamespace: default
    serving.knative.dev/service: hello
  name: hello.default.knative.ts.anhdle14.me
  namespace: default
spec:
  hostnames:
  - hello.default.knative.ts.anhdle14.me
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    sectionName: http # <----------------- CAN SEPCIFY THE LISTENER HERE. BUT MISSING.
    name: knative-gateway
    namespace: istio-system
  rules:
  - backendRefs:
    - filters:
      - requestHeaderModifier:
          set:
          - name: Knative-Serving-Revision
            value: hello-00001
          - name: Knative-Serving-Namespace
            value: default
        type: RequestHeaderModifier
      group: ""
      kind: Service
      name: hello-00001
      port: 80
      weight: 100
    filters:
    - requestHeaderModifier:
        set:
        - name: K-Network-Hash
          value: d5e6e76864e0485d5d3e37426c6f081d0efba24af58e6a9285cb6cc55cb64dc9
      type: RequestHeaderModifier
    matches:
    - headers:
      - name: K-Network-Hash
        type: Exact
        value: override
      path:
        type: PathPrefix
        value: /
  - backendRefs:
    - filters:
      - requestHeaderModifier:
          set:
          - name: Knative-Serving-Revision
            value: hello-00001
          - name: Knative-Serving-Namespace
            value: default
        type: RequestHeaderModifier
      group: ""
      kind: Service
      name: hello-00001
      port: 80
      weight: 100
    matches:
    - path:
        type: PathPrefix
        value: /
```

</details>

Could we provide anyway to allow `config-gateway` to allow some templates to be used when generating `*Route` resource?

_Originally posted by @anhdle14 in https://github.com/knative-sandbox/net-gateway-api/issues/367#issuecomment-1493420989_
