### ISSUE TITLE
Add cilium to conformance testing 

### ISSUE THREAD

**Issue by acelinkio** [knative-extensions/net-gateway-api#553]
Please add Cilium into knative's testing of the gatewayapi.

[Cilium](https://github.com/cilium/cilium) is a CNI, kube-proxy replacement, sidecar-less service mesh, load balancer, and observability tool that also offers a gateway controller.  Cilium 1.15 will support all gateway-api features except for one as seen in their conformance report, https://github.com/kubernetes-sigs/gateway-api/blob/main/conformance/reports/v0.8.1/cilium-cilium.yaml.

Cilium is growing in popularity and leverages some of the most recent Linux features.  Greatly appreciate if it could be added and regularly tested against Knative!

**Comment by bittermandel** [comment]
Happy to help out with the implementation of this! We're looking to use Cilium for Gateway API and it feels like the best way to make it work with Knative.

**Comment by acelinkio** [comment]
hey @tomaszkiewicz, thanks for opening the filters issue.  I have that working but not sure how to configure the rest of this project to work with Cilium.  Would you happen to have an example of how you setup Knative?

I had kourier ingress working, but not understanding how to get the gateway setup functioning.  If anyone has any working examples that would be great!


my setup:  https://github.com/acelinkio/argocd-homelab/blob/main/manifest/knative-serving.yaml

**Comment by tomaszkiewicz** [comment]
Hi, sure: I simply followed a readme on this repository to deploy both KNative as well as all the settings, then fine tuned some of them in `config-gateway` config map:

```yaml
 visibility: |                                                   
   ExternalIP:                                                   
     class: cilium                                               
     gateway: default/cilium-gateway                             
     service: default/cilium-gateway-cilium-gateway              
   ClusterLocal:                                                 
     class: cilium                                               
     gateway: default/cilium-gateway                             
     service: default/cilium-gateway-cilium-gateway                                               
```

Then I created a gateway object like that:

```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: cilium-gateway
spec:
  gatewayClassName: cilium
  listeners:
    - protocol: HTTP
      port: 80
      name: web
```
