### ISSUE TITLE
Envoy Gateway doesn't work with Knative

### ISSUE THREAD

**Issue by dprotaso** [knative-extensions/net-gateway-api#813]
This is a tracking issue for an upstream bug - https://github.com/envoyproxy/gateway/issues/5230

/triage accepted

**Comment by arkodg** [comment]
should be resolved, can you try again @dprotaso ?
also can we update https://github.com/knative-extensions/net-gateway-api/blob/58602c7f4535941420ef5a23e6f30aec6a2f556a/hack/test-env.sh#L23 to use `v0.0.0-latest` so its easier to track any regression in the future

**Comment by kahirokunn** [comment]
I verified it in v1.5.4, and it is functioning normally.

**Comment by em-sav** [comment]
Hey @kahirokunn, how did you get this to work? I'm running a simple test with EnvoyGateway to expose a service over HTTP, but I'm getting `503` errors at the gateway. 

```
envoy [2026-01-11T03:48:07.547Z] "GET /status/200 HTTP/1.1" 503 - 0 0 0 "172.18.0.1" "curl/8.7.1" "24a970d8-fbf9-4738-8892-5481afce1598" "knative-serving.cncf.demo" "-"
envoy [2026-01-11T03:48:25.624Z] "GET / HTTP/1.1" 503 - 0 0 0 "10.244.1.22" "Knative-Ingress-Probe" "6f58ca98-c491-4167-bd3e-3075ec2ab38d" "knative-serving.cncf.demo" "-"
```

I've been experiencing this issue for a while with EG and suspect that the [host-rewrite](https://github.com/knative-extensions/net-gateway-api/blob/main/hack/test-env.sh#L24) functionality isn't working properly with EnvoyGateway as mention.

My **External HTTPRoute** appears to be configured correctly, but the `urlRewrite` that should forward requests to the **Internal HTTPRoute** doesn't seem to be functioning. Both routes are generated by Knative through the net-gateway-api plugin using my `DomainMapping` and `Claim`.

<details>
<summary>Domain Mapping + Claim</summary>

```yaml
apiVersion: networking.internal.knative.dev/v1alpha1
kind: ClusterDomainClaim
metadata:
  name: knative-serving.cncf.demo
spec:
  namespace: workload
---
apiVersion: serving.knative.dev/v1beta1
kind: DomainMapping
metadata:
  name: knative-serving.cncf.demo
  namespace: workload
spec:
  ref:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: cncf-server
    namespace: workload
```
</details>

<details>
<summary>External HTTPRoute</summary>

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: knative-serving.cncf.demo
  namespace: workload
spec:
  hostnames:
  - knative-serving.cncf.demo
  parentRefs:
  - name: knative-gateway
    namespace: gateway
  rules:
  - backendRefs:
    - filters:
      - requestHeaderModifier:
          set:
          - name: K-Original-Host
            value: knative-serving.cncf.demo
        type: RequestHeaderModifier
      name: cncf-server
      port: 80
    filters:
    - requestHeaderModifier:
        set:
        - name: K-Network-Hash
          value: fbc466689545331b7d591abca1ae387f5d09e481e1f946ab0cbcda76e0106397
      type: RequestHeaderModifier
    - type: URLRewrite
      urlRewrite:
        hostname: cncf-server.workload.svc.cluster.local
    matches:
    - headers:
      - name: K-Network-Hash
        type: Exact
        value: override
      path:
        type: PathPrefix
        value: /
    timeouts:
      request: 0s
  - backendRefs:
    - filters:
      - requestHeaderModifier:
          set:
          - name: K-Original-Host
            value: knative-serving.cncf.demo
        type: RequestHeaderModifier
      name: cncf-server
      port: 80
    filters:
    - type: URLRewrite
      urlRewrite:
        hostname: cncf-server.workload.svc.cluster.local
    matches:
    - path:
        type: PathPrefix
        value: /
    timeouts:
      request: 0s
```
</details>

<details>
<summary>Internal HTTPRoute</summary>

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: cncf-server.workload.svc.cluster.local
  namespace: workload
spec:
  hostnames:
  - cncf-server.workload
  - cncf-server.workload.svc
  - cncf-server.workload.svc.cluster.local
  parentRefs:
  - name: knative-gateway
    namespace: gateway
  rules:
  - backendRefs:
    - filters:
      - requestHeaderModifier:
          set:
          - name: Knative-Serving-Namespace
            value: workload
          - name: Knative-Serving-Revision
            value: cncf-server-00001
        type: RequestHeaderModifier
      name: cncf-server-00001
      port: 80
    filters:
    - requestHeaderModifier:
        set:
        - name: K-Network-Hash
          value: 59076927154f9e22aad8fbc09413773dfc0344b403172b1597a0daec07ee2724
      type: RequestHeaderModifier
    matches:
    - headers:
      - name: K-Network-Hash
        type: Exact
        value: override
      path:
        type: PathPrefix
        value: /
    timeouts:
      request: 0s
  - backendRefs:
    - filters:
      - requestHeaderModifier:
          set:
          - name: Knative-Serving-Namespace
            value: workload
          - name: Knative-Serving-Revision
            value: cncf-server-00001
        type: RequestHeaderModifier
      name: cncf-server-00001
      port: 80
    matches:
    - path:
        type: PathPrefix
        value: /
    timeouts:
      request: 0s
```
</details>

When I test from inside the cluster, Knative works as expected by scaling the `Pod` and sending traffic to the right revision by going through the internal-knative-gateway: `curl http://cncf-server.workload.svc.cluster.local`

cc: @dprotaso 🙏
