### ISSUE TITLE
Kingress fails to reconcile with http-option set to Redirected

### ISSUE THREAD

**Issue by divanikus** [knative-extensions/net-gateway-api#818]
I'm trying to use Knative with wildcard TLS per namespace. My network configuration is the following:

```
  config:
    network:
      ingress-class: "gateway-api.ingress.networking.knative.dev"
      domain-template: "{{.Name}}.{{.Namespace}}.{{.Domain}}"
      auto-tls: "Enabled"
      http-protocol: "Redirected"
      default-external-scheme: "https"
      namespace-wildcard-cert-selector: "{\"matchExpressions\": [{\"key\":\"networking.knative.dev/enableWildcardCert\", \"operator\": \"In\", \"values\":[\"true\"]}]}"
```
In this case external gateways gives me 404 on any requests to port 80. Which also makes the reconciler to fail with wrong return code

```
"logger":"net-gateway-api-controller","caller":"status/status.go:463","message":"Probing of http://hello.default.example.com/ failed, IP: 10.2.70.129:80, ready: false, error: unexpected status code: want 200, got 404 (depth: 0)"
```
Switching `http-protocol` to `Enabled` fixes the problem.

Knative version: **1.17.0**
